[versions]
kotlin-jvm = "2.0.21"
shadow-jar = "8.3.5"
fastutil = "8.5.15"
plugin-yml = "0.6.0"
run-paper = "2.3.1"
run-velocity = "2.3.1"
commandapi-bukkit = "9.7.0"
commandapi-bukkit-kotlin = "9.7.0"
commandapi-velocity = "9.7.1-SNAPSHOT"
commandapi-velocity-kotlin = "9.7.1-SNAPSHOT"
paper-api = "1.21.4-R0.1-SNAPSHOT"
paperweight = "1.7.4"
velocity-api = "3.4.0-SNAPSHOT"
coroutines = "1.9.0"
mccoroutine-velocity = "2.20.0"
mccoroutine-folia = "2.20.0"
hibernate = "6.6.2.Final"
hibernate-hikari = "6.6.2.Final"
jakarta-transactions = "2.0.1"
mariadb = "3.5.0"
caffeine = "3.1.8"
caffeine-coroutines = "1.2.0"
autoservice = "1.1.1"
packetuxui = "1.0.1-SNAPSHOT"
repo-auth = "3.0.4"
kaml = "0.67.0"
adventure-api = "4.17.0"
adventure-gson = "4.17.0"
adventure-logger = "4.17.0"
gson = "2.11.0"

paper-server = "1.21.4"
velocity-server = "3.4.0-SNAPSHOT"
commandapi-server = "9.7.0"
mckotlin-server = "Z25PwYNh"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-jvm" }
kotlin-serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin-jvm" }
shadow-jar = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow-jar" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
plugin-yml = { module = "net.minecrell:plugin-yml", version.ref = "plugin-yml" }
run-paper = { module = "xyz.jpenilla:run-task", version.ref = "run-paper" }
run-velocity = { module = "xyz.jpenilla:run-task", version.ref = "run-velocity" }
commandapi-bukkit = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi-bukkit" }
commandapi-bukkit-kotlin = { module = "dev.jorel:commandapi-bukkit-kotlin", version.ref = "commandapi-bukkit-kotlin" }
commandapi-velocity = { module = "dev.jorel:commandapi-velocity-shade", version.ref = "commandapi-velocity" }
commandapi-velocity-kotlin = { module = "dev.jorel:commandapi-velocity-kotlin", version.ref = "commandapi-velocity-kotlin" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
paperweight = { module = "io.papermc.paperweight:paperweight-userdev", version.ref = "paperweight" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
mccoroutine-velocity = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-api", version.ref = "mccoroutine-velocity" }
mccoroutine-velocity-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-core", version.ref = "mccoroutine-velocity" }
mccoroutine-folia = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-api", version.ref = "mccoroutine-folia" }
mccoroutine-folia-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-core", version.ref = "mccoroutine-folia" }
hibernate = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
hibernate-hikari = { module = "org.hibernate:hibernate-hikaricp", version.ref = "hibernate-hikari" }
jakarta-transactions = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transactions" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-gson" }
adventure-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure-logger" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
caffeine-coroutines = { module = "dev.hsbrysk:caffeine-coroutines", version.ref = "caffeine-coroutines" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }
packetuxui = { module = "dev.slne:packetuxui-bukkit", version.ref = "packetuxui" }
repo-auth = { module = "org.hibernate.build.maven-repo-auth:org.hibernate.build.maven-repo-auth.gradle.plugin", version.ref = "repo-auth" }
kaml = { module = "com.charleskorn.kaml:kaml-jvm", version.ref = "kaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }